name: Prepare Release

on:
  push:
    tags:
      - 'v*' # Create a release for tags starting with 'v'

jobs:
  guard:
    name: Usage guard
    runs-on: ubuntu-latest
    steps:
      # Uses the action-usage-guard action
      - name: Run Action Usage Guard
        uses: nekofar/action-usage-guard@develop
        with:
          # GitHub access token for authentication.
          token: ${{ secrets.ACCESS_TOKEN }}
          # Defines the threshold for the usage guard.
          threshold: 70

  lint:
    name: Code quality
    runs-on: ubuntu-latest
    needs: [ guard ]
    steps:
      # Checks-out the repository
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      # Runs ShellCheck on all shell scripts in your repository
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  draft:
    name: Draft a release
    runs-on: ubuntu-latest
    needs: [ lint ]
    permissions:
      contents: write
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      # Generate a changelog for the new release using Git
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4.3.0
        id: git-cliff
        with:
          config: cliff.toml # The configuration file for git-cliff
          args: -vv --latest --strip all # Show verbose output, grab the latest changes, and strip unnecessary details
        env:
          OUTPUT: CHANGES.md # The output file for the changelog

      # Prepare release notes by processing the generated changelog
      - name: Set the release notes
        id: release
        shell: bash
        run: |
          # Read contents of changelog into variable 'r'
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          # Remove first two lines from 'r'
          r="$(printf "$r" | tail -n +3)"
          # Save the value of 'r' back into the GitHub environment output
          {
              echo "notes<<EOF"
              echo "$r"
              echo "EOF"
          } >> $GITHUB_OUTPUT

      # Create a new GitHub release using the gathered information
      - name: Create the release
        uses: nekofar/create-github-release@develop
        with:
          token: ${{ github.token }} # Authentication token from GitHub
          tag: ${{ github.ref_name }} # The name of the tag to be released
          title: ${{ github.ref_name }} # The title for the release
          notes: ${{ steps.release.outputs.notes }} # The release notes generated in the previous step
          draft: true # The release will be created as a draft
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }} # Conditions to mark the release as a pre-release
